#!/bin/sh

### BEGIN INIT INFO
# Provides:     robot_web_server
# Required-Start:   networking
# Required-Stop:
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Description:     Web server for streaming camera images and controlling robotic hardware
### END INIT INFO

HOME=/root
DIR=/home/pi/raspberry_pi_camera_bot
DAEMON=$DIR/robot_web_server.py
DAEMON_NAME=robot_web_server
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile \
         --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg "$?"
    ;;
  stop)
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg "$?"
    ;;
  restart)
    $0 stop
    sleep 8
    $0 start
    ;;
  status)
    status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
    exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
